### ISSUE TITLE
d2dlibexport - missing dll reference

### ISSUE THREAD

**Issue by Diemongo** [jingwood/d2dlib#10]
I think your latest commit of binaries has some issues. When I use these, I get a reference error, where d2dlibexport is complaining about a missing reference (d2dlib.dll). When I place your previous version, there is no errors.

**Comment by jingwood** [comment]
I've tested with some projects, don't see problems. Can you post the error message?

**Comment by Diemongo** [comment]
You have the error here:
"Error Could not load file or assembly 'file:///C:\Libs\d2dlibexport.dll' or one of its dependencies. Operation is not supported. (Exception from HRESULT: 0x80131515)"

The path is shortened here for ease, but in the real solution I have a Libs folder with the two files d2dlibexport.dll and D2DLibWinform.dll - where the file d2dlib.dll is placed at the root of my solution, and is copied during build. This way the all exist at the same folder level in the bin folder.

Please notice, that this setup is never changed - I just overwrite the three files with your latest binaries.

- o -

A final thing: You're using version number 1.0.1.0 for d2dlibexport.dll and D2DLibWinform.dll - where 
the d2dlib.dll is version 1.0.0.1

If these files always have a common dependency, I'd suggest you keep single common version number for all files - and always increment it at every new release/upload. 
I't will make a lot easier while debugging to reference the exact version causing the trouble.

/Per

**Comment by BaddSyntax** [comment]
Just FYI, I'm using the latest version and have had no such issues.  Runs great!

Wish there was some way to render to a windows handle though, like a form or picturebox, instead of having to create a new form.

**Comment by jingwood** [comment]
I have update all the binaries to `1.1.0.0`, is there still any problems?
