### ISSUE TITLE
Why carry an unmanaged library instead of just wrapping Direct2D in pure C#?

### ISSUE THREAD

**Issue by sgf** [jingwood/d2dlib#112]
Why carry an unmanaged library instead of just wrapping Direct2D in pure C#?

**Comment by jingwood** [comment]
I think it 's for something profits on performance and development side.
There are too many interface should be wrapped for calling from pure C#, including functions, structures and enums, etc.
To do something low-level operations, managed C# might be slower, such as pointer or memory handles.

**Comment by sgf** [comment]
But this affects the number of application dlls.
And it may also have an impact on AOT.
But this may be a matter of personal preference.
Thank you for your answer.
