### ISSUE TITLE
 please add FillRoundedRectangle method

### ISSUE THREAD

**Issue by Hot-key** [jingwood/d2dlib#14]
I want to draw a round rectangle.

If possible, can I add ID2D1RenderTarget::FillRoundRectangle method?

A docs about [FillRoundedRectangle](https://docs.microsoft.com/en-us/windows/win32/api/d2d1/nf-d2d1-id2d1rendertarget-fillroundedrectangle(constd2d1_rounded_rect__id2d1brush))

**Comment by jingwood** [comment]
Sure! you can free feel to provide Pull requests for any changes!

**Comment by jingwood** [comment]
Now we have the `DrawRoundedRect` method, thanks!
