### ISSUE TITLE
Memory leak in CreateBitmapFromGDIBitmap()

### ISSUE THREAD

**Issue by nicolasdejong** [jingwood/d2dlib#16]
I'm using this library for a project that opens and closes a D2DForm often. It uses GDI bitmaps to cache because they are expensive to create and I don't want to wait for that when opening the window.

I noticed the equivalent of the code below leads to a memory leak. The below code should, if I understand it correctly, have the same memory use before and after. Unfortunately that seems not to be the case:

```
Bitmap bitmap = new Bitmap(1000, 1000);
D2DBitmap d2dBitmap = Device.CreateBitmapFromGDIBitmap(bitmap);
d2dBitmap.Dispose();
bitmap.Dispose();
```

Is this a memory leak or am I doing something wrong and is there another way to reclaim the used memory? Perhaps there is a workaround?

**Comment by nicolasdejong** [comment]
Turns out, this line is the culprit:

`D2D.CreateBitmapFromHBitmap(this.Handle, bmp.GetHbitmap(), useAlphaChannel);
`

where the GetHbitmap() is not freed.

I have fixed the method and created a pull request for it.

**Comment by jingwood** [comment]
#17
