### ISSUE TITLE
Does it support 64 bit?

### ISSUE THREAD

**Issue by d2phap** [jingwood/d2dlib#18]
Does it support 64 bit?
I got this warning when install on x64 project

![image](https://user-images.githubusercontent.com/3154213/75102793-366ec400-562c-11ea-8548-cd6af9060804.png)

```
There was a mismatch between the processor architecture of the project being built "AMD64" and the processor architecture of the reference "d2dlibexport, Version=1.2.0.4064, Culture=neutral, processorArchitecture=x86", "x86". This mismatch may cause runtime failures. Please consider changing the targeted processor architecture of your project through the Configuration Manager so as to align the processor architectures between your project and references, or take a dependency on references with a processor architecture that matches the targeted processor architecture of your project.
```

**Comment by jingwood** [comment]
The 64-bit binaries have been added here:
https://github.com/jingwood/d2dlib/tree/master/binary/x64-build

Currently, when source code has been changed, the 64-bit binaries will not be updated just time. But anytime you can build the 64-bit binaries from the source code yourself.

**Comment by d2phap** [comment]
thank you!
