### ISSUE TITLE
Building x64 does not copy d2dlib64.dll to Examples output

### ISSUE THREAD

**Issue by fire-eggs** [jingwood/d2dlib#23]
1. Open d2dlib.sln as from github
2. Set target to Debug, x64.
3. Build solution.
4. Set Examples as startup project, execute.
5. Click on any demo.

Exception: d2dlib64.dll missing.
Look at src\examples\bin\x64\debug folder: d2dlib64.dll is not there.

**Comment by jingwood** [comment]
Thanks a lot! now fixed.
