### ISSUE TITLE
Error in D2DLib.vcxproj: creating d2dlib6464.dll for Debug x64

### ISSUE THREAD

**Issue by fire-eggs** [jingwood/d2dlib#24]
Error in the project settings for D2DLib project, x64 Debug.

Output file is set to: `$(OutDir)$(TargetName)64$(TargetExt)` which results in creating `d2dlib6464.dll`.

Should be set to: `$(OutDir)$(TargetName)$(TargetExt)` [or removed?]

**Comment by jingwood** [comment]
Thanks very much! fixed now.
