### ISSUE TITLE
Measuring String

### ISSUE THREAD

**Issue by nikeee** [jingwood/d2dlib#26]
Is it possible to measure a string inside the `OnRender` of a `D2DForm`?

**Comment by jingwood** [comment]
@nikeee There is a very simple API `measureText` has been added. But I am planning to add more support such as font styles as well as performance improvement. You can just try it now.

A sample code to measure and drawing text.
```
var text = "Hello World";
var rect = new Rectangle(100, 100, 500, 500);

var measuredSize = g.MeasureText(text, font1.Name, font1.Size, rect.Size);
var measuredRect = new D2DRect(rect.X, rect.Y, measuredSize.width, measuredSize.height);

g.DrawText(text, D2DColor.Black, font1.Name, font1.Size, rect);
g.DrawRectangle(measuredRect, D2DColor.Blue);
```
Result:
![image](https://user-images.githubusercontent.com/3468046/80714353-c8fd7900-8b2f-11ea-876e-7f8c0aeff54f.png)

**Comment by nikeee** [comment]
Awesome! Thank you!
