### ISSUE TITLE
How to use D2DControl as PictureBox? Help me please,  please...

### ISSUE THREAD

**Issue by matheustkful** [jingwood/d2dlib#32]
Hey friend, very good?
I am trying D2DControl use as Picturebox and dont work.
I create the CustomControl and i edit. See the image:
[https://imgur.com/6VxS1sE](url)
I select the D2dControl in ToolBox and put in form design. But show the following errror:
[https://imgur.com/4VPG7Dx](url)
[https://imgur.com/XbAunDp](url)

**Comment by jingwood** [comment]
Hi! your pictures cannot be displayed correctly.

`D2DForm` and `D2DControl` cannot be use in design-time, you can create an empty file and use the following code to make your own control.

```csharp
class MyControl : D2DControl {
  ...
}
```

And you have to draw image and other else inside the `OnRender` method:

```csharp
protected virtual void OnRender(D2DGraphics g) { 
  ...
}
```
