### ISSUE TITLE
Inverse Matrix

### ISSUE THREAD

**Issue by Unreal852** [jingwood/d2dlib#35]
Is it possible to invert matrix ? ( C# lib ). Actually i'm drawing rectangles, and using Translate and Scale to allow Pan & Zoom. Thats working, but i can't calculate mouse position because the rectangles positions changed via the Matrix translate but there is no way to also translate mouse pos (or i didn't find how).

**Comment by jingwood** [comment]
I have added an example code to do the hit-test using an inverse transformation.
You may have to create a completed transformation system to draw objects and perform the hit-test for every objects.

I think an common method is to make objects have transform property and its inverse. e.g.:

- Object
  - Local position
  - Transform (Matrix3x3)
  - Inverse Transform (Matrix3x3)

To draw the object:
```csharp
g.setTransform(obj.Transform);
g.drawRect(...);
```

To hit-test point:
```csharp
var transformedPoint = obj.InverseTransform.TransformPoint(p);
bool isHitted = rect.ContainsPoint(transformedPoint);
```

I have also added two new APIs `SetTransform` and `GetTransform` to set and get a transform into Direct2D context.
You can get a transform during drawing object and calculate the inverse for hit-test.
The Direct2D receives a 3x2 matrix which can be simply converted from a 3x3 matrix.

Here is the [example code](//github.com/jingwood/d2dlib/blob/master/src/Examples/Demos/HitTestByInverseTransform.cs)

**Comment by Unreal852** [comment]
Working like a charm ! Thanks
