### ISSUE TITLE
Fillpolygon does not work

### ISSUE THREAD

**Issue by BergChristian** [jingwood/d2dlib#46]
Hi!

Created an array of D2Dpoints and try to draw it.

drawpolygon works fine
But fillpolygon causes that nothing is being rendered at all. Does not get an error message.

Any ideas why it happens?

Best
Christian

**Comment by BergChristian** [comment]
Hi!

Solved. There are two versions. One which accepts a color and the other which takes a brush. The brush ones works great but the color one does not. 

Best
Christian

**Comment by jingwood** [comment]
Thanks! I think it is a bug and I will fix it as soon as possible.

**Comment by jingwood** [comment]
I have fixed this bug. But since performance reason the `FillPolygon` has been marked as obsoleted, you can use 'DrawPolygon' instead.

**Comment by BergChristian** [comment]
Ok! would it be possible to achieve a filled polygon using draw polygon? In my case it is not that many arrows so it does not affect my performance but good to know 👍 .
