### ISSUE TITLE
Inverse Matrix in the Demo does not work when scaling

### ISSUE THREAD

**Issue by Unreal852** [jingwood/d2dlib#48]
Hi, i used the Matrix3 provided in the [Demo](https://github.com/jingwood/d2dlib/blob/master/src/Examples/Demos/HitTestByInverseTransform.cs) but when scaling it, the inverse matrix does not work, or maybe i'm doing it wrong . Here is how i update my matrix

```CSharp
Matrix.LoadIdentity();
Matrix.Scale(ViewZoom, ViewZoom);
Matrix.Translate(ViewPosition.X, ViewPosition.Y);
InverseMatrix.CopyFrom(Matrix).Inverse();
```

**Comment by jingwood** [comment]
Yes I can confirm the bug, let me fix it...

**Comment by drewnoakes** [comment]
Could potentially use [`System.Numerics.Vectors`](https://www.nuget.org/packages/System.Numerics.Vectors) instead.

**Comment by jingwood** [comment]
Added the scale feature, as well as new feature for drag-to-move.
![image](https://user-images.githubusercontent.com/3468046/106278051-5ca9d480-627d-11eb-8b20-c26896a9ed89.png)

Thanks @drewnoakes! I haven't been noticed there is a built-in numeric library. Now It has been to use the System.Numeric.* instead.
