### ISSUE TITLE
Adding multiple D2DControls is too slow

### ISSUE THREAD

**Issue by MineEric64** [jingwood/d2dlib#51]
Hi, I'm trying to add multiple (a hundred) d2dcontrols in my form.

but it's too slow.
It took 4100ms for adding `D2DControl` and my custom control `D2DButton`.
But it just took 100ms for adding `Button` class. (in System.Windows.Forms)

Why it is too slow?
Also I used suspend & resume layout, but it didn't work for me.

I tested in this code (vb.net):
```vb.net
Public Sub TestOnButton(testCount As Integer, useLayout As Boolean)
        Dim rand As New Random()

        If useLayout Then
            Me.SuspendLayout()
        End If

        For i = 1 To testCount
            Dim btn As New TestButton() With {
                    .Text = i.ToString(),
                    .Location = New Point(rand.Next(0, Me.Width), rand.Next(0, Me.Height))
                    }

            Me.Controls.Add(btn)
        Next

        If useLayout Then
            Me.ResumeLayout()
        End If
    End Sub
```

```vb.net
Imports TestButton = unvell.D2DLib.WinForm.D2DControl
TestOnButton(100, False)
```
4100ms elapsed

```vb.net
Imports TestButton = System.Windows.Forms.Button
TestOnButton(100, False)
```
100ms elapsed

thanks.

**Comment by MineEric64** [comment]
also, I tested one more thing.

```vb.net
Imports TestButton = unvell.D2DLib.WinForm.D2DControl
TestOnButton(1, False)
```
130ms elapsed

```vb.net
Imports TestButton = System.Windows.Forms.Button
TestOnButton(1, False)
```
1ms elapsed

**Comment by jingwood** [comment]
I don't think it is a good idea to create many D2DControl instances and add them onto a Windows Form. The D2DControl is designed to individually hold a hardware associated handler (device), which is expensive. In this case you may won't get any performance benefit.

I am not sure what is your final goal, but if you can create a single D2DForm window and your own button components to handle the user's mouse event, such as click or hover, I think that would be a better implementation.

**Comment by MineEric64** [comment]
oh I got it.
thanks for reply this issue :)

**Comment by MineEric64** [comment]
I fixed this issue using d2d form instead of winform.

thanks!!
