### ISSUE TITLE
Import HBitmap directly?

### ISSUE THREAD

**Issue by BergChristian** [jingwood/d2dlib#57]
Hi!

I am capture the screen and trying to present the captured image in a D2DImage. Everything works fine, but the question is if it can be more efficient.

Right now I am getting a hBitmap from the Cope screen function, which I convert into a GDI which I send to D2D image which converts it back to an hbitmap?

Do you think there could be an option to feed the hbitmap directly?

    success = BitBlt(memoryDc, 0, 0, region.Width, region.Height, desktopDc, region.Left, region.Top, RasterOperations.SRCCOPY Or RasterOperations.CAPTUREBLT)

        D2Dimage.Dispose()
        D2Dimage = Nothing
        D2Dimage = device.CreateBitmapFromGDIBitmap(image.FromHbitmap(bitmap))

Best
Christian

   Dim desktophWnd As IntPtr
        Dim desktopDc As IntPtr
        Dim memoryDc As IntPtr
        Dim bitmap As IntPtr
        Dim oldBitmap As IntPtr
        Dim success As Boolean
            'Dim result As Bitmap
            desktophWnd = GetDesktopWindow()
        desktopDc = GetWindowDC(desktophWnd)
        memoryDc = CreateCompatibleDC(desktopDc)
        bitmap = CreateCompatibleBitmap(desktopDc, region.Width, region.Height)
        oldBitmap = SelectObject(memoryDc, bitmap)

        success = BitBlt(memoryDc, 0, 0, region.Width, region.Height, desktopDc, region.Left, region.Top, RasterOperations.SRCCOPY Or RasterOperations.CAPTUREBLT)

        D2Dimage.Dispose()
        D2Dimage = Nothing
        D2Dimage = device.CreateBitmapFromGDIBitmap(image.FromHbitmap(bitmap))

        SelectObject(memoryDc, oldBitmap)
        DeleteObject(bitmap)
        DeleteDC(memoryDc)
        ReleaseDC(desktophWnd, desktopDc)

**Comment by jingwood** [comment]
I have added a new API method `CreateBitmapFromHBitmap`, you can try this method from latest source code.

```vbsharp
D2Dimage = device.CreateBitmapFromHBitmap(hbitmap)
```

2b4f395063af1bfcf283d059e6e545f1723adbf2

**Comment by BergChristian** [comment]
Thanks! 
Way much faster and more importantly less memory usage. An awesome library just got better!

Christian

**Comment by BergChristian** [comment]
And.. Thanks for the link. I wanted to capture a region of the screen. Trying to capture a window but having issues with application which are hardware rendered so right now the best effort is to capture a part of a screen but I really would like to capture a window and the content of it rather than the screen.

**Comment by jingwood** [comment]
Glad to hear that works.
