### ISSUE TITLE
DrawText aspect ratio problem

### ISSUE THREAD

**Issue by channel11** [jingwood/d2dlib#68]
When the Direct2D control height is small, the drawn font is squeezed, and the top part cut off.

g.DrawText("Hello World \nsecond line", D2DColor.Black, font, 100, 200);

<img width="353" alt="squeeze" src="https://user-images.githubusercontent.com/9476280/127761993-cb045d19-a568-433f-9787-eae586eba69f.png">

**Comment by jingwood** [comment]
Hi, Can you tell me what font you are using? Because in my environment there seems no problems to me.
And your windows environment information such as scale (DPI), resolution. Thanks.

**Comment by jingwood** [comment]
Close this issue, if you still have problem please reopen or create a new.
