### ISSUE TITLE
Rendering a transparent cleared image over another removes the original image?

### ISSUE THREAD

**Issue by ItsEddie** [jingwood/d2dlib#7]
Hey there,

It's me again, hopefully not bothering you with this one. It appears that when I render an image cleared using the Graphics.Clear method over another image, it removes the original image.

```
                   e.Graphics.DrawBitmap(
                        Snippit.Image,
                        new D2DRect(0, 0, form.DesktopBounds.Width, form.DesktopBounds.Height),
                        new D2DRect(form.DesktopBounds.Left, form.DesktopBounds.Top, form.DesktopBounds.Width, form.DesktopBounds.Height)
                    );
                    /*e.Graphics.FillRectangle(
                        new D2DRect(
                            form.DisplayRectangle.Left,
                            form.DisplayRectangle.Top,
                            form.DisplayRectangle.Width,
                            form.DisplayRectangle.Height
                        ),
                        overlayColor
                    );*/
                    e.Graphics.DrawBitmap(
                        Canvas,
                        new D2DRect(0, 0, form.DesktopBounds.Width, form.DesktopBounds.Height),
                        new D2DRect(form.DesktopBounds.Left, form.DesktopBounds.Top, form.DesktopBounds.Width, form.DesktopBounds.Height)
                    );

```

I should be seeing the Snippit.Image as the background, but instead I'm recieving a gray-ish looking color with the Canvas on top of it.

![image](https://user-images.githubusercontent.com/20602971/44203964-292c6b80-a151-11e8-880d-2cf6667e95fb.png)

I've already double checked if the image I'm overlaying is actually transparent, and it is. 

This is the image being overlayed.
![hello](https://user-images.githubusercontent.com/20602971/44204013-4f520b80-a151-11e8-8d71-2b7ab599d36f.png)

This might be a bug within the API I'm not sure.

   ```
         if (Canvas == null || Canvas.Width != Snippit.Image.Width && Canvas.Height != Snippit.Image.Height)
            {
                Canvas?.Dispose();
                CanvasGraphics?.Dispose();

                Canvas = new Bitmap(
                    Snippit.Image.Width,
                    Snippit.Image.Height
                );

                CanvasGraphics = Graphics.FromImage(Canvas);
                CanvasGraphics.CompositingQuality = CompositingQuality.HighQuality;
                CanvasGraphics.SmoothingMode = SmoothingMode.HighQuality;
                CanvasGraphics.InterpolationMode = InterpolationMode.HighQualityBicubic;
            }

            CanvasGraphics.Clear(Color.Transparent);

            Canvas.Save("hello.png");
```

Regards,
 - Eddie

**Comment by jingwood** [comment]
If you are trying to draw .NET bitmap, make sure the bitmap is created with `Format32bppPArgb`  specified. Like this:
https://github.com/jingwood/d2dlib/blob/master/src/Examples/Demos/BitmapCustomDraw.cs#L43

Btw. How about if you publish your project to a GitHub repository, so that I can download and debug your application in a more easy way.

**Comment by ItsEddie** [comment]
I'd be alright with emailing you the code. I don't have an upgraded version of GitHub and can't make a private repository because of that. Anyways, I've just converted every instance of a bitmap in my code to that **PixelFormat** and it didn't resolve the issue - tried it before, but I didn't change **all** of them.

**Comment by ItsEddie** [comment]
I also have Dropbox if that works for you.

**Comment by ItsEddie** [comment]
Do you mind giving me your email address so I could send you the code? I've tried everything now and it's just not solving the issue. All images being drawn are in the specified pixel format. Been looking at this for about 5 hours now.

**Comment by jingwood** [comment]
Sure, you can send to jing@reogrid.net

**Comment by ItsEddie** [comment]
I've send you an email. I'm considering this issue resolved because so far this is likely an issue on my side!
