### ISSUE TITLE
Problem with optimization when i change the windows form resolution.

### ISSUE THREAD

**Issue by FinishtT** [jingwood/d2dlib#72]

**Comment by nikeee** [comment]
Could you please elaborate?

**Comment by FinishtT** [comment]
I love this library !

i'm stuck at 60 fps with d2dlib when i draw on my winform simple to understand.

I look the exemple and same problem.

**Comment by FinishtT** [comment]
I use a software reading and changing the resolution with the specified attached window.

When i change my resolution to 1920x1080p the render is so slow.. who i optimize that ? thank you ! :)
