### ISSUE TITLE
CreateTextLayout causes Memory Leak

### ISSUE THREAD

**Issue by MightyM7** [jingwood/d2dlib#79]
Hi,

the function CreateTextLayout in Text.cpp causes a memory leak by not releasing the textFormat in case of returning the textLayout (line 87).

Old:

`		if (SUCCEEDED(hr) && textLayout != NULL) {
			return (HANDLE)textLayout;
		}`

Correct:

`		if (SUCCEEDED(hr) && textLayout != NULL) {
			SafeRelease(&textFormat);
			return (HANDLE)textLayout;
		}`

Regards

**Comment by jingwood** [comment]
Thanks!
