### ISSUE TITLE
Memory exception when loading transparent bitmap

### ISSUE THREAD

**Issue by BaddSyntax** [jingwood/d2dlib#8]
When I try to render a PNG with an alpha channel, I get an access violation exception.

I do something like this:
```
Dim Thing As New Bitmap("filename.png")
Dim bmp = Device.CreateBitmapGraphics(screenImageWidth, screenImageHeight)
bmp.beginrender
bmp.DrawBitmap(Thing, New D2DRect(0, 0, Thing.Width - 1, Thing.Height - 1), 1, True, D2DBitmapInterpolationMode.Linear)
bmp.endrender
```

System.AccessViolationException: 'Attempted to read or write protected memory. This is often an indication that other memory is corrupt.'

If I just change that one value to False to not show alpha, it works, but of course the bitmap shows no transparency layer.

Any idea how to fix that?  Or an alternate way to load a PNG with an alpha channel and render it properly?

I really appreciate the effort you have done here.  Since MSFT stopped supporting DX in VB it has crippled my efforts to do some projects.

**Comment by jingwood** [comment]
@BaddSyntax 

Thanks for pointing out. Fixed. Now you can use the code above without any changes and keep passing `True`, it should works. Please download the latest source code or binary DLLs.

By the way, if you draw the PNG file many times, you can firstly convert it to Direct2D bitmap, draw Direct2D bitmap will giving you higher rendering performance.

```vb
Dim Thing As New Bitmap("filename.png")
Dim d2bmp = Device.CreateBitmapFromGDIBitmap(Thing)
bmp.DrawBitmap(d2bmp, ...
```

**Comment by BaddSyntax** [comment]
Thanks for that quick update, you rock!

I was able to convert an old GDI app into D2D relatively easily, and it runs great.  My only beef is that I can't bind the render window to a picturebox or form, as it would have been nice to support rending 2 screens on 2 monitors independently.

But GREAT work, I really appreciate it as well as your tip.

**Comment by fluffapparition** [comment]
K
