### ISSUE TITLE
Feature request: DrawPie and FillPie

### ISSUE THREAD

**Issue by MightyM7** [jingwood/d2dlib#80]
Hi,

could you please implement DrawPie and FillPie like e.g. described here:
[https://docs.microsoft.com/en-us/dotnet/api/system.drawing.graphics.fillpie?view=dotnet-plat-ext-6.0](url)

Thank you.

Regards

**Comment by jingwood** [comment]
It sounds nice.

Before it get implemented you may consider use the simple path API like this:
https://github.com/jingwood/d2dlib/issues/33

**Comment by MightyM7** [comment]
Thank you for answering. It this as fast as DrawPie/FillPie?

**Comment by jingwood** [comment]
Close this issue, if you still have problem please reopen or create a new.
